import type { Metadata } from "next";
import './index.scss';
import Navbar from './components/Navbar'
import Header from './components/Header'
import Footer from './components/Footer'

export const metadata: Metadata = {
  title: "Joea Com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
