import type { Metadata } from "next";
import './index.scss';
import './loader.scss';

import dynamic from 'next/dynamic';
import Loader from "./components/Loader";
import { Suspense } from "react";
import Loading from "./Loading";

export const metadata: Metadata = {
  title: "Joea Com",
  description: "Generated by create next app",
};

// Charger les composants de manière asynchrone avec suspense
const Navbar = dynamic(() => import('./components/Navbar'), { suspense: true });
const Header = dynamic(() => import('./components/Header'), { suspense: true });
const Footer = dynamic(() => import('./components/Footer'), { suspense: true });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<Loading />}>
          <Header />
          <Navbar />
          {children}
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
